default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: pttime_development
test:
  <<: *default
  database: pttime_test
production:
  <<: *default
  database: pttime_production
