# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfb3df46db0811e91c8826ae9aed6f3b6e88b5dc7d74ec4825e783e8ac8b0b13d0385bdfef0952c41e1398c24b81f55af355866c53c3f5c0598abb3ed51a1b3a

test:
  secret_key_base: 9ca0cacff9c0cd17584049c656e72ee8b743b56c931bfbd3257dd133b373b5b5d6d9f7673886c153e623a0f7bc64e35f598f5c21b704861872acb2c6aac687b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
