# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af93d958c67593aa9726f02bacb8a48c2a73cac5e5849fdb8e951a606de4faa9cb85cdd8e6821539141a5b6856c320f04684abc1165a69ce292199ded3970cc9

test:
  secret_key_base: 0077dc48215b38ce9a18f81caae8947ee72ecd5b800e4a13c5c09dd1f5f567d1e69cb0fc7d0cfc8a735bbcce99112417c0dc85003f57d8bb66ebd7be0d6b84ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
